setw -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Status line configuration
set -g status-style bg="#272822",fg="#F8F8F2"

set -g status-left "#[fg=color7,bg=color1] #S #[default]"
set -g status-left-length 50

set -g status-justify centre
setw -g window-status-format "#[fg=color8]#I #W"
setw -g window-status-current-format "#[fg=color2]#I #W"

set -g status-right "#[fg=color0,bg=color2] %H:%M #[fg=color7,bg=color8] #(tmux-time) "
set -g status-right-length 50
